project:
  type: website
  output-dir: docs 

website:
  title: "Soyeon Jin"
  navbar:
    search: false
    left:
      - href: index.qmd
        text: Home
      - href: files/CV.pdf
        text: CV
      - publication.qmd
      - teaching.qmd
      - Extra.qmd
    tools:
      - icon: twitter
        href: https://x.com/SoyeonJin3
      - icon: github
        href: https://github.com/sojin3
format:
  html:
    theme: litera
    css: styles.css
    toc: true
