---
title: "Publications"
---



# Journal articles

- **Corbu, N., Halagiera, D., Jin, S., et al. (2025)** Illusory superiority about misinformation detection and its relationship to knowledge and fact-checking intentions: Evidence from 18 countries. *Mass Communication & Society*, Forthcoming.  

- **Jin, S. (2024).** Why Is Immigration Important to You? A Revisit To Public Issue Salience and Elite Cues. *European Journal of Political Research.* [Open access](https://ejpr.onlinelibrary.wiley.com/doi/full/10.1111/1475-6765.12708 ) 

- **Jin, S., Zilinsky, J., Pradel, F., & Theocharis, Y. (2024).** Beliefs in Conspiracy Theories and Online News Consumption during the onset of the COVID-19 pandemic. *Journal of Quantitative Description: Digital Media, 4.* [link](https://journalqd.org/article/view/3318) 

- **Matthes, J., Corbu, N., Jin, S., et al. (2023).** Perceived prevalence of misinformation fuels worries about COVID-19: a cross-country, multi-method investigation. *Information, Communication & Society, 26*(16), 3133-3156. [Open access](https://www.tandfonline.com/doi/full/10.1080/1369118X.2022.2146983) 

- **Theocharis, Y., Cardenal, A., Jin, S., et al. (2023).** Does the platform matter? Social media and COVID-19 conspiracy theory beliefs in 17 countries. *New Media & Society, 25*(12), 3412-3437. [Open access](https://journals.sagepub.com/doi/full/10.1177/14614448211045666) 


# Working Papers

-  Beyond the Ballot: Media Consumption and Immigrants’ Political Participation in Germany (Single author paper. *(Single-author paper)*
